'use client';

import Link from 'next/link';
import { Activity, ArrowDown, ArrowRight, Check, ChevronRight, FileText, HeartPulse, Menu, Plus, Stethoscope, Video, X } from 'lucide-react';
import { useState } from 'react';
import { useTelehealth } from '../context/TelehealthContext';

export default function HomePage() {
  const { currentUser } = useTelehealth();
  const [menuOpen, setMenuOpen] = useState(false);
  const portal = currentUser?.role?.toLowerCase() === 'doctor' ? '/doctor/dashboard' : '/patient/dashboard';
  const entry = currentUser ? portal : '/auth';
  return (
    <div className="care-home min-h-screen overflow-x-clip bg-[#f9fbf8] text-slate-900">
      <a className="care-skip" href="#main-content">Skip to content</a>
      <header className="border-b border-slate-200/70 bg-[#f9fbf8]/95">
        <div className="mx-auto flex h-20 max-w-7xl items-center justify-between px-5 sm:px-8">
          <Link href="/" aria-label="CuraLink home" className="flex items-center gap-2.5 text-xl font-bold tracking-tight"><span className="flex size-10 items-center justify-center rounded-2xl bg-teal-800 text-white"><HeartPulse size={23} /></span>CuraLink<span className="mt-1 size-1.5 rounded-full bg-teal-600" /></Link>
          <nav aria-label="Main navigation" className="hidden items-center gap-8 text-sm font-medium text-slate-600 md:flex"><a href="#how-it-works" className="hover:text-teal-800">How it works</a><a href="#your-care" className="hover:text-teal-800">Your care</a><Link href="/auth?role=doctor" className="hover:text-teal-800">For clinicians</Link></nav>
          <div className="flex items-center gap-4"><Link href={entry} className="hidden text-sm font-semibold text-teal-900 sm:block">{currentUser ? 'My dashboard' : 'Sign in'}</Link><Link href={entry} className="care-button hidden sm:inline-flex">{currentUser ? 'Open portal' : 'Get started'}<ArrowRight size={16} /></Link><button type="button" onClick={() => setMenuOpen(!menuOpen)} className="rounded-xl p-2 md:hidden" aria-label={menuOpen ? 'Close navigation' : 'Open navigation'} aria-expanded={menuOpen} aria-controls="home-mobile-menu">{menuOpen ? <X /> : <Menu />}</button></div>
        </div>
        {menuOpen && <nav id="home-mobile-menu" aria-label="Mobile navigation" className="grid gap-1 border-t border-slate-200 px-5 py-4 md:hidden">{[['How it works', '#how-it-works'], ['Your care', '#your-care'], ['For clinicians', '/auth?role=doctor'], [currentUser ? 'My dashboard' : 'Sign in', entry]].map(([label, href]) => <Link key={label} href={href} onClick={() => setMenuOpen(false)} className="rounded-lg px-3 py-3 text-sm font-semibold hover:bg-teal-50">{label}</Link>)}</nav>}
      </header>
      <main id="main-content">
        <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 py-16 sm:px-8 sm:py-24 lg:grid-cols-[1fr_1.05fr] lg:gap-10 lg:py-28">
          <div className="relative z-10">
            <span className="mb-7 inline-flex items-center gap-2 rounded-full border border-teal-800/15 bg-white px-3.5 py-2 text-xs font-semibold text-teal-800"><span className="size-2 rounded-full bg-teal-600" />A little closer to better care</span>
            <h1 className="max-w-xl text-5xl font-semibold leading-[1.08] tracking-[-0.055em] sm:text-6xl xl:text-7xl">Feel better.<br /><span className="text-teal-800">Stay connected.</span></h1>
            <p className="mt-6 max-w-md text-base leading-7 text-slate-600 sm:text-lg">Your doctor, health records, and daily readings. Together in one thoughtful space, wherever life takes you.</p>
            <div className="mt-9 flex flex-wrap items-center gap-4"><Link href={entry} className="care-button px-6 py-3.5">{currentUser ? 'Go to my dashboard' : 'Start your care journey'}<ArrowRight size={18} /></Link><a href="#how-it-works" className="inline-flex items-center gap-2 rounded-xl px-3 py-3.5 text-sm font-semibold text-slate-700">See how it works<ArrowDown size={16} /></a></div>
            <div className="mt-8 flex flex-wrap gap-x-6 gap-y-3 text-xs font-medium text-slate-600"><span className="flex items-center gap-1.5"><Check size={15} className="text-teal-700" />Virtual consultations</span><span className="flex items-center gap-1.5"><Check size={15} className="text-teal-700" />Connected health records</span></div>
          </div>
          <div className="relative mx-auto w-full max-w-xl lg:pl-4"><div className="absolute -inset-6 rounded-[45%] bg-[#e1eee5] sm:-inset-10" aria-hidden="true" /><div className="relative overflow-hidden rounded-3xl border border-white bg-white shadow-[0_25px_80px_-25px_rgba(28,74,63,0.25)]">
            <div className="flex items-center justify-between gap-2 border-b border-slate-100 px-5 py-4"><span className="flex items-center gap-2 text-sm font-semibold"><HeartPulse size={19} className="text-teal-700" />Your health, at a glance</span><span className="rounded-full bg-slate-100 px-2.5 py-1 text-[10px] font-semibold text-slate-500">Illustrative preview</span></div>
            <div className="p-5 sm:p-7"><div className="flex items-start justify-between gap-3"><div><p className="text-xs text-slate-500">A place for your everyday health</p><h2 className="mt-1.5 text-2xl font-semibold tracking-tight">Good care starts here.</h2></div><span className="flex size-10 shrink-0 items-center justify-center rounded-full bg-amber-50 text-amber-700"><Plus size={20} /></span></div>
              <div className="mt-6 rounded-2xl bg-teal-800 p-5 text-white"><div className="flex items-center gap-2 text-xs text-teal-100"><Video size={16} />Your next consultation</div><div className="mt-4 flex items-center justify-between gap-3"><div><p className="text-lg font-semibold">A conversation that matters</p><p className="mt-1 text-xs text-teal-100">Meet your care team from home</p></div><span className="flex size-11 shrink-0 items-center justify-center rounded-full bg-white/15"><ArrowRight size={20} /></span></div></div>
              <div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-2xl border border-slate-200 p-4"><span className="flex items-center gap-2 text-xs font-medium text-slate-500"><Activity size={16} className="text-teal-700" />Daily readings</span><p className="mt-3 text-base font-semibold sm:text-lg">See the bigger picture</p><svg viewBox="0 0 220 48" className="mt-3 w-full text-teal-600" aria-hidden="true"><path d="M0 35 Q15 35 25 28 T50 30 T75 24 T100 27 T125 15 T150 18 T175 10 T200 13 L220 7" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" /></svg></div><div className="rounded-2xl border border-slate-200 p-4"><span className="flex items-center gap-2 text-xs font-medium text-slate-500"><FileText size={16} className="text-teal-700" />Health records</span><p className="mt-3 text-base font-semibold sm:text-lg">Everything in its place</p><div className="mt-4 space-y-2" aria-hidden="true"><div className="h-2 w-4/5 rounded bg-slate-100" /><div className="h-2 w-3/5 rounded bg-slate-100" /><div className="h-2 w-2/3 rounded bg-teal-50" /></div></div></div>
              <div className="mt-5 flex items-center gap-3 rounded-xl bg-[#f6f8f5] px-4 py-3"><span className="flex size-8 shrink-0 items-center justify-center rounded-full bg-white text-teal-700"><Stethoscope size={17} /></span><p className="text-xs leading-5 text-slate-600">Connected tools. A more personal care experience.</p></div>
            </div>
          </div></div>
        </section>
        <section id="your-care" className="border-y border-slate-200/70 bg-white"><div className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="care-eyebrow">CARE, WITHOUT THE COMPLICATIONS</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">One place. More peace of mind.</h2></div><p className="max-w-sm text-sm leading-6 text-slate-500">Less time keeping track. More time focusing on what matters to you.</p></div><div className="mt-10 grid gap-5 md:grid-cols-3">{[
          { icon: Video, title: 'Your doctor, within reach', text: 'Book a consultation and join your video visit from the same space.', link: '/patient/appointments', label: 'Explore consultations', color: 'bg-[#eaf3ec]' },
          { icon: Activity, title: 'Know your everyday health', text: 'Connect your supported device and keep your readings in view over time.', link: '/patient/device', label: 'Explore connected care', color: 'bg-[#f9f1e4]' },
          { icon: FileText, title: 'A clearer health story', text: 'Keep documents, clinical notes, and prescriptions together for your next visit.', link: '/patient/records', label: 'Explore health records', color: 'bg-[#edf1f8]' },
        ].map(({ icon: Icon, title, text, link, label, color }) => <article key={title} className="rounded-2xl border border-slate-200 p-7"><span className={`flex size-12 items-center justify-center rounded-2xl text-teal-900 ${color}`}><Icon size={23} /></span><h3 className="mt-7 text-xl font-semibold tracking-tight">{title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{text}</p><Link href={currentUser ? link : '/auth'} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-teal-800">{label}<ChevronRight size={17} /></Link></article>)}</div></div></section>
        <section id="how-it-works" className="mx-auto max-w-7xl px-5 py-16 sm:px-8 sm:py-20"><p className="care-eyebrow">A SIMPLE START</p><h2 className="mt-3 text-3xl font-semibold tracking-tight sm:text-4xl">Your next step to feeling supported.</h2><div className="mt-10 grid gap-9 md:grid-cols-3">{[['01', 'Make yourself at home', 'Create an account and tell us a little about your health.'], ['02', 'Connect with your care team', 'Choose a verified clinician and schedule a time that works for you.'], ['03', 'Keep your care moving', 'Find your visit notes, prescriptions, and readings whenever you need them.']].map(([number, title, text]) => <div key={number}><span className="text-sm font-semibold text-teal-700">{number}<span className="ml-3 inline-block h-px w-20 bg-teal-800/20 align-middle" /></span><h3 className="mt-4 text-lg font-semibold">{title}</h3><p className="mt-2 max-w-sm text-sm leading-6 text-slate-500">{text}</p></div>)}</div></section>
        <section className="mx-auto mb-16 max-w-7xl px-5 sm:px-8"><div className="flex flex-col items-start justify-between gap-7 rounded-3xl bg-[#e7efe7] p-8 sm:p-12 md:flex-row md:items-center"><div><p className="care-eyebrow">BUILT AROUND PEOPLE</p><h2 className="mt-3 text-3xl font-semibold tracking-tight">Better connected. Better supported.</h2><p className="mt-3 text-sm text-slate-600">A thoughtful workspace for patients and the clinicians who care for them.</p></div><Link href={entry} className="care-button shrink-0">{currentUser ? 'Open my portal' : 'Get started with CuraLink'}<ArrowRight size={17} /></Link></div></section>
      </main>
      <footer className="border-t border-slate-200 bg-white"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-6 px-5 py-8 sm:flex-row sm:items-center sm:px-8"><div><Link href="/" className="flex items-center gap-2 font-bold"><HeartPulse size={21} className="text-teal-800" />CuraLink</Link><p className="mt-2 text-xs text-slate-500">Thoughtful tools for connected care.</p></div><nav aria-label="Footer navigation" className="flex flex-wrap gap-6 text-sm text-slate-600"><Link href="/auth">Patient sign in</Link><Link href="/auth?role=doctor">Clinician sign in</Link><Link href="/admin">Administration</Link></nav></div></footer>
    </div>
  );
}
