import {
  UserProfile,
  Appointment,
  Prescription,
  MedicalRecord,
  PatientDirectoryItem,
  LiveTelemetryPayload,
  VitalHistoryPoint,
} from './types';

export const MOCK_PATIENT_USER: UserProfile = {
  uid: 'patient_sarah_jenkins_01',
  fullName: 'Sarah Jenkins',
  email: 'sarah.jenkins@telehealth.org',
  phoneNumber: '+1 (555) 349-8821',
  role: 'Patient',
  dateOfBirth: '1988-06-14',
  bloodType: 'O Positive',
  emergencyContact: 'Mark Jenkins (Spouse) - +1 (555) 902-1144',
  allergies: ['Penicillin', 'Sulfa Drugs'],
  assignedDoctorId: 'doc_marcus_vance_01',
};

export const MOCK_DOCTOR_USER: UserProfile = {
  uid: 'doc_marcus_vance_01',
  fullName: 'Dr. Marcus Vance, MD',
  email: 'dr.vance@curalink.health',
  phoneNumber: '+1 (555) 880-9922',
  role: 'Doctor',
  specialty: 'Cardiology & Intensive Care',
  licenseNumber: 'MD-CA-9938210',
};

export const MOCK_DOCTORS_LIST = [
  {
    id: 'doc_marcus_vance_01',
    name: 'Dr. Marcus Vance, MD',
    specialty: 'Cardiology & Heart Rhythm',
    rating: 4.9,
    reviewsCount: 142,
    avatar: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=150&auto=format&fit=crop&q=80',
    hospital: 'CuraLink Central Cardiac Center',
    availableToday: true,
  },
  {
    id: 'doc_elena_rostova_02',
    name: 'Dr. Elena Rostova, MD',
    specialty: 'Pulmonology & Respiratory Care',
    rating: 4.8,
    reviewsCount: 98,
    avatar: 'https://images.unsplash.com/photo-1594824813633-91104e76d353?w=150&auto=format&fit=crop&q=80',
    hospital: 'Metropolitan Telehealth Institute',
    availableToday: true,
  },
  {
    id: 'doc_aravind_sharma_03',
    name: 'Dr. Aravind Sharma, MD',
    specialty: 'General Internal Medicine',
    rating: 5.0,
    reviewsCount: 215,
    avatar: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=150&auto=format&fit=crop&q=80',
    hospital: 'Apex TeleCare General Clinic',
    availableToday: false,
  },
  {
    id: 'doc_claire_dubois_04',
    name: 'Dr. Claire Dubois, MD',
    specialty: 'Neurology & Sleep Medicine',
    rating: 4.9,
    reviewsCount: 110,
    avatar: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=150&auto=format&fit=crop&q=80',
    hospital: 'Pacific Neurocare Hospital',
    availableToday: true,
  },
];

export const INITIAL_LIVE_TELEMETRY: LiveTelemetryPayload = {
  deviceId: 'ESP32-CURALINK-NODE-01',
  patientId: 'patient_sarah_jenkins_01',
  timestamp: Date.now(),
  heartRate: 76,
  spo2: 98.2,
  temperature: 36.7,
  systolic: 122,
  diastolic: 79,
  batteryLevel: 94,
  sensorConnected: true,
  status: 'normal',
  alertMessage: undefined,
};

export const MOCK_VITALS_24H_TREND: VitalHistoryPoint[] = [
  { time: '00:00', heartRate: 64, spo2: 98, temperature: 36.5, systolic: 118, diastolic: 76 },
  { time: '02:00', heartRate: 62, spo2: 98, temperature: 36.4, systolic: 116, diastolic: 74 },
  { time: '04:00', heartRate: 60, spo2: 97, temperature: 36.3, systolic: 115, diastolic: 73 },
  { time: '06:00', heartRate: 68, spo2: 98, temperature: 36.5, systolic: 119, diastolic: 77 },
  { time: '08:00', heartRate: 78, spo2: 99, temperature: 36.7, systolic: 124, diastolic: 80 },
  { time: '10:00', heartRate: 82, spo2: 98, temperature: 36.8, systolic: 125, diastolic: 81 },
  { time: '12:00', heartRate: 75, spo2: 98, temperature: 36.9, systolic: 121, diastolic: 79 },
  { time: '14:00', heartRate: 85, spo2: 97, temperature: 37.0, systolic: 126, diastolic: 82 },
  { time: '16:00', heartRate: 79, spo2: 98, temperature: 36.8, systolic: 122, diastolic: 78 },
  { time: '18:00', heartRate: 76, spo2: 99, temperature: 36.7, systolic: 120, diastolic: 77 },
  { time: '20:00', heartRate: 74, spo2: 98, temperature: 36.6, systolic: 119, diastolic: 76 },
  { time: '22:00', heartRate: 69, spo2: 98, temperature: 36.5, systolic: 117, diastolic: 75 },
];

export const MOCK_APPOINTMENTS: Appointment[] = [
  {
    id: 'apt_101',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_marcus_vance_01',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorSpecialty: 'Cardiology & Heart Rhythm',
    date: 'Today, Oct 4',
    time: '04:30 PM - 05:00 PM',
    type: 'Video Call',
    status: 'Upcoming',
    symptoms: 'Post-cardiac stent follow up and routine IoT telemetry review.',
    meetingLink: 'https://meet.curalink.health/room-vance-jenkins',
  },
  {
    id: 'apt_102',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_elena_rostova_02',
    doctorName: 'Dr. Elena Rostova, MD',
    doctorSpecialty: 'Pulmonology',
    date: 'Wednesday, Oct 8',
    time: '11:00 AM - 11:30 AM',
    type: 'Video Call',
    status: 'Upcoming',
    symptoms: 'Seasonal asthma control and SpO2 sensor baseline analysis.',
    meetingLink: 'https://meet.curalink.health/room-rostova-jenkins',
  },
  {
    id: 'apt_103',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_aravind_sharma_03',
    doctorName: 'Dr. Aravind Sharma, MD',
    doctorSpecialty: 'General Internal Medicine',
    date: 'Sep 22, 2026',
    time: '02:00 PM - 02:30 PM',
    type: 'Video Call',
    status: 'Completed',
    symptoms: 'Annual health checkup and lipid panel prescription refill.',
  },
];

export const MOCK_DOCTOR_APPOINTMENTS_QUEUE: Appointment[] = [
  {
    id: 'apt_101',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_marcus_vance_01',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorSpecialty: 'Cardiology & Heart Rhythm',
    date: 'Today, Oct 4',
    time: '04:30 PM',
    type: 'Video Call',
    status: 'Upcoming',
    symptoms: 'Post-cardiac stent follow up and routine IoT telemetry review.',
    meetingLink: 'https://meet.curalink.health/room-vance-jenkins',
  },
  {
    id: 'apt_104',
    patientId: 'patient_david_miller_02',
    patientName: 'David Miller',
    doctorId: 'doc_marcus_vance_01',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorSpecialty: 'Cardiology',
    date: 'Today, Oct 4',
    time: '05:15 PM',
    type: 'Video Call',
    status: 'Upcoming',
    symptoms: 'Intermittent arrhythmia reported by smartwatch sensor.',
    meetingLink: 'https://meet.curalink.health/room-vance-miller',
  },
  {
    id: 'apt_105',
    patientId: 'patient_robert_chen_03',
    patientName: 'Robert Chen',
    doctorId: 'doc_marcus_vance_01',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorSpecialty: 'Cardiology',
    date: 'Today, Oct 4',
    time: '06:00 PM',
    type: 'In-Person Consultation',
    status: 'Upcoming',
    symptoms: 'In-clinic Doppler echocardiogram check.',
  },
];

export const MOCK_PRESCRIPTIONS: Prescription[] = [
  {
    id: 'rx_89012',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_marcus_vance_01',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorLicense: 'MD-CA-9938210',
    medicationName: 'Atorvastatin Calcium',
    dosage: '20 mg Oral Tablet',
    frequency: 'Once daily at bedtime',
    duration: '90 Days',
    instructions: 'Take with or without food. Avoid excessive grapefruit consumption.',
    dateIssued: 'Sep 24, 2026',
    validUntil: 'Dec 24, 2026',
    refillsLeft: 2,
    status: 'Active',
  },
  {
    id: 'rx_89013',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_marcus_vance_01',
    doctorName: 'Dr. Marcus Vance, MD',
    doctorLicense: 'MD-CA-9938210',
    medicationName: 'Metoprolol Succinate ER',
    dosage: '25 mg Extended-Release',
    frequency: 'Once daily in the morning',
    duration: '60 Days',
    instructions: 'Take with breakfast. Monitor resting heart rate via CuraLink IoT monitor.',
    dateIssued: 'Oct 01, 2026',
    validUntil: 'Nov 30, 2026',
    refillsLeft: 1,
    status: 'Active',
  },
  {
    id: 'rx_89010',
    patientId: 'patient_sarah_jenkins_01',
    patientName: 'Sarah Jenkins',
    doctorId: 'doc_aravind_sharma_03',
    doctorName: 'Dr. Aravind Sharma, MD',
    doctorLicense: 'MD-NY-7728109',
    medicationName: 'Amoxicillin Trihydrate',
    dosage: '500 mg Capsule',
    frequency: 'Three times daily after meals',
    duration: '10 Days',
    instructions: 'Complete entire 10-day course even if symptoms subside.',
    dateIssued: 'Aug 10, 2026',
    validUntil: 'Aug 20, 2026',
    refillsLeft: 0,
    status: 'Completed',
  },
];

export const MOCK_MEDICAL_RECORDS: MedicalRecord[] = [
  {
    id: 'rec_5510',
    patientId: 'patient_sarah_jenkins_01',
    date: 'Oct 02, 2026',
    type: 'Lab Report',
    title: 'Comprehensive Metabolic & Lipid Panel',
    doctorName: 'Dr. Marcus Vance, MD',
    facility: 'CuraLink Diagnostic Lab #4',
    fileSize: '1.8 MB (PDF)',
    summary: 'Total cholesterol 178 mg/dL (Normal). eGFR > 90 mL/min. Electrolytes balanced.',
  },
  {
    id: 'rec_5509',
    patientId: 'patient_sarah_jenkins_01',
    date: 'Sep 18, 2026',
    type: 'Clinical Summary',
    title: 'Echocardiogram & Cardiac Stress Report',
    doctorName: 'Dr. Marcus Vance, MD',
    facility: 'Pacific Telehealth Cardiology Wing',
    fileSize: '3.4 MB (PDF)',
    summary: 'Left ventricular ejection fraction (LVEF) 60%. Normal systolic function.',
  },
  {
    id: 'rec_5508',
    patientId: 'patient_sarah_jenkins_01',
    date: 'Aug 04, 2026',
    type: 'Radiology',
    title: 'Chest X-Ray Digital Imaging & Reading',
    doctorName: 'Dr. Elena Rostova, MD',
    facility: 'Metropolitan Imaging Center',
    fileSize: '5.1 MB (DICOM/PDF)',
    summary: 'Clear bilateral lung fields. No pleural effusion or cardiomegaly detected.',
  },
];

export const MOCK_PATIENT_DIRECTORY: PatientDirectoryItem[] = [
  {
    id: 'patient_sarah_jenkins_01',
    name: 'Sarah Jenkins',
    age: 36,
    gender: 'Female',
    condition: 'Post-Stent / Hypertension Control',
    status: 'Stable',
    roomOrBed: 'Remote Tele-Unit #104',
    assignedDoctor: 'Dr. Marcus Vance, MD',
    lastVisit: 'Oct 01, 2026',
    nextAppointment: 'Today 04:30 PM',
    currentVitals: {
      heartRate: 76,
      spo2: 98.2,
      temperature: 36.7,
      bloodPressure: '122/79',
    },
  },
  {
    id: 'patient_david_miller_02',
    name: 'David Miller',
    age: 58,
    gender: 'Male',
    condition: 'Atrial Fibrillation / Anticoagulated',
    status: 'Monitored',
    roomOrBed: 'Remote Tele-Unit #212',
    assignedDoctor: 'Dr. Marcus Vance, MD',
    lastVisit: 'Sep 29, 2026',
    nextAppointment: 'Today 05:15 PM',
    currentVitals: {
      heartRate: 94,
      spo2: 96.5,
      temperature: 37.1,
      bloodPressure: '138/88',
    },
  },
  {
    id: 'patient_elizabeth_taylor_03',
    name: 'Elizabeth Taylor',
    age: 72,
    gender: 'Female',
    condition: 'Congestive Heart Failure (NYHA II)',
    status: 'Critical',
    roomOrBed: 'Remote ICU-Link #08',
    assignedDoctor: 'Dr. Marcus Vance, MD',
    lastVisit: 'Oct 03, 2026',
    nextAppointment: 'Tomorrow 09:00 AM',
    currentVitals: {
      heartRate: 114,
      spo2: 92.1,
      temperature: 38.6,
      bloodPressure: '152/95',
    },
  },
  {
    id: 'patient_michael_chang_04',
    name: 'Michael Chang',
    age: 44,
    gender: 'Male',
    condition: 'Type 2 Diabetes & Early Neuropathy',
    status: 'Stable',
    roomOrBed: 'Remote Tele-Unit #305',
    assignedDoctor: 'Dr. Aravind Sharma, MD',
    lastVisit: 'Sep 15, 2026',
    nextAppointment: 'Oct 12, 2026',
    currentVitals: {
      heartRate: 72,
      spo2: 99.0,
      temperature: 36.6,
      bloodPressure: '120/78',
    },
  },
];
