'use client';

import { useState } from 'react';
import { FileText, Search } from 'lucide-react';
import { useTelehealth } from '../../context/TelehealthContext';
import { fieldClass, normalizeWorkspaceRecords, RecordAttachment, textValue, WorkspaceDataNotice, WorkspaceDialog } from './DoctorWorkspaceSupport';

export function DoctorMedicalRecords() {
  const { clinicalRecords, patientDirectory, dataLoading } = useTelehealth();
  const [search, setSearch] = useState('');
  const [recordType, setRecordType] = useState('All');
  const [patientId, setPatientId] = useState('All');
  const [selectedId, setSelectedId] = useState('');
  const records = normalizeWorkspaceRecords(clinicalRecords, patientDirectory);
  const types = ['All', ...Array.from(new Set(records.map((record) => record.type)))];
  const filtered = records.filter((record) => (record.title + ' ' + record.patientName + ' ' + record.type).toLowerCase().includes(search.trim().toLowerCase()) && (recordType === 'All' || record.type === recordType) && (patientId === 'All' || record.patientId === patientId));
  const selected = records.find((record) => record.id === selectedId);
  const prescriptionFields = selected ? [['Medication', textValue(selected.content.medicationName)], ['Dosage', textValue(selected.content.dosage)], ['Frequency', textValue(selected.content.frequency)], ['Duration', textValue(selected.content.duration)], ['Instructions', textValue(selected.content.instructions)]].filter(([, value]) => value) : [];

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="care-eyebrow mb-2">A connected care history</p><h1 className="text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl">Medical records</h1><p className="mt-2 text-sm text-slate-500">Documents, prescriptions, and clinical notes for your assigned patients.</p></div><span className="w-fit rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs text-slate-500">{dataLoading ? 'Loading…' : records.length + ' shared records'}</span></div>
      <WorkspaceDataNotice />
      <div className="care-card grid gap-3 p-4 md:grid-cols-[minmax(0,1fr)_200px_220px]"><div className="relative"><label htmlFor="record-search" className="sr-only">Search medical records</label><Search size={17} className="absolute left-3 top-3.5 text-slate-400" aria-hidden="true" /><input id="record-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by document or patient name" className={fieldClass + ' pl-9'} /></div><label className="sr-only" htmlFor="record-type-filter">Record type</label><select id="record-type-filter" value={recordType} onChange={(event) => setRecordType(event.target.value)} className={fieldClass}>{types.map((type) => <option key={type} value={type}>{type === 'All' ? 'All record types' : type}</option>)}</select><label className="sr-only" htmlFor="record-patient-filter">Patient</label><select id="record-patient-filter" value={patientId} onChange={(event) => setPatientId(event.target.value)} className={fieldClass}><option value="All">All assigned patients</option>{patientDirectory.map((patient) => <option key={patient.id} value={patient.id}>{patient.name}</option>)}</select></div>
      {!filtered.length ? <div className="care-card px-5 py-16 text-center"><span className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-50 text-teal-700"><FileText size={25} aria-hidden="true" /></span><h2 className="text-base font-semibold text-slate-800">{dataLoading ? 'Loading medical records' : records.length ? 'No matching records' : 'Care records, together'}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-slate-500">{records.length ? 'Try another search or select a different record type.' : 'Shared documents and notes from your care relationships will appear here.'}</p></div> : <ul className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((record) => <li key={record.id} className="care-card flex flex-col p-5"><div className="flex items-start justify-between gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-xl bg-teal-50 text-teal-700"><FileText size={21} aria-hidden="true" /></span><span className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] text-slate-500">{record.type}</span></div><h2 className="mt-4 text-base font-semibold text-slate-900">{record.title}</h2><p className="mt-1 text-xs text-teal-800">{record.patientName}</p><p className="mt-2 text-[11px] text-slate-400">{record.date}{record.doctorName && ' · ' + record.doctorName}</p>{record.notes && <p className="mt-3 line-clamp-3 text-xs leading-relaxed text-slate-500">{record.notes}</p>}<div className="mt-5 flex flex-wrap items-center justify-between gap-2 border-t border-slate-100 pt-4"><button type="button" onClick={() => setSelectedId(record.id)} className="min-h-10 rounded-lg text-xs font-semibold text-teal-800 focus-visible:outline-2 focus-visible:outline-teal-700">View record</button>{record.attachment && <RecordAttachment record={record} />}</div></li>)}</ul>}
      {selected && <WorkspaceDialog title={selected.title} onClose={() => setSelectedId('')}><div className="space-y-5"><div className="flex flex-wrap gap-2"><span className="rounded-full bg-teal-50 px-2.5 py-1 text-[10px] text-teal-800">{selected.type}</span><span className="rounded-full bg-slate-50 px-2.5 py-1 text-[10px] text-slate-500">{selected.date}</span></div><div><p className="text-sm font-semibold text-slate-900">{selected.patientName}</p>{selected.doctorName && <p className="mt-1 text-xs text-slate-500">Recorded by {selected.doctorName}</p>}</div>{selected.notes && <div><h3 className="mb-2 text-xs font-semibold text-slate-700">Clinical notes</h3><p className="whitespace-pre-wrap rounded-xl bg-slate-50 p-4 text-sm leading-relaxed text-slate-600">{selected.notes}</p></div>}{prescriptionFields.length > 0 && <dl className="grid gap-3 sm:grid-cols-2">{prescriptionFields.map(([label, value]) => <div key={label} className="rounded-xl border border-slate-200 p-3"><dt className="text-[10px] font-semibold text-slate-400">{label}</dt><dd className="mt-2 whitespace-pre-wrap text-sm text-slate-700">{value}</dd></div>)}</dl>}<RecordAttachment record={selected} preview /></div></WorkspaceDialog>}
    </div>
  );
}
