'use client';

import { useState } from 'react';
import { Calendar, FileText, Mail, Phone, Plus, Search, Users, Video } from 'lucide-react';
import type { Appointment, PatientDirectoryItem } from '../../lib/types';
import { useTelehealth } from '../../context/TelehealthContext';
import { activeAppointmentStatuses, ClinicalNoteDialog, fieldClass, hasRecordedVitals, normalizeWorkspaceRecords, PatientHistory, RecordAttachment, WorkspaceDataNotice, WorkspaceDialog } from './DoctorWorkspaceSupport';

interface PatientDirectoryProps {
  patients?: PatientDirectoryItem[];
  onStartVideoCall?: (appointment: Appointment) => void;
  onOpenEHR?: (patientName: string, patientId?: string) => void;
}

export function PatientDirectory({ onStartVideoCall, onOpenEHR }: PatientDirectoryProps) {
  const { patientDirectory, doctorAppointmentsQueue, clinicalRecords, dataLoading, openEHR } = useTelehealth();
  const [search, setSearch] = useState('');
  const [filter, setFilter] = useState<'All' | 'With readings' | 'Needs attention'>('All');
  const [selectedId, setSelectedId] = useState('');
  const [notePatient, setNotePatient] = useState<{ id: string; name: string } | null>(null);
  const selected = patientDirectory.find((patient) => patient.id === selectedId);
  const hasReadings = hasRecordedVitals;
  const filtered = patientDirectory.filter((patient) => (patient.name + ' ' + (patient.email || '') + ' ' + (patient.condition || '')).toLowerCase().includes(search.trim().toLowerCase()) && (filter === 'All' || (filter === 'With readings' ? hasReadings(patient) : patient.status === 'Critical')));
  const records = normalizeWorkspaceRecords(clinicalRecords, patientDirectory);
  const selectedRecords = records.filter((record) => record.patientId === selected?.id);
  const videoAppointment = (patientId: string) => doctorAppointmentsQueue.find((appointment) => appointment.patientId === patientId && appointment.type === 'Video Call' && activeAppointmentStatuses.has(appointment.status.toLowerCase()));
  const prescribe = (patient: PatientDirectoryItem) => (onOpenEHR || openEHR)(patient.name, patient.id);

  return (
    <div className="mx-auto max-w-7xl space-y-6">
      <div className="flex flex-col justify-between gap-3 sm:flex-row sm:items-center"><div><p className="care-eyebrow mb-2">People in your care</p><h1 className="text-2xl font-semibold tracking-tight text-slate-900 sm:text-3xl">My patients</h1><p className="mt-2 text-sm text-slate-500">Review recorded health information, notes, and shared documents.</p></div><span className="w-fit rounded-full border border-slate-200 bg-white px-3 py-1.5 text-xs text-slate-500">{dataLoading ? 'Loading…' : patientDirectory.length + ' assigned patients'}</span></div>
      <WorkspaceDataNotice />
      <div className="care-card flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="relative flex-1"><label htmlFor="patient-search" className="sr-only">Search assigned patients</label><Search size={17} className="absolute left-3 top-3.5 text-slate-400" aria-hidden="true" /><input id="patient-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search by name, email, or condition" className={fieldClass + ' pl-9'} /></div><div className="flex flex-wrap gap-1 rounded-xl bg-slate-50 p-1" aria-label="Filter patients">{(['All', 'With readings', 'Needs attention'] as const).map((value) => <button type="button" key={value} aria-pressed={filter === value} onClick={() => setFilter(value)} className={`min-h-9 rounded-lg px-3 text-xs font-medium focus-visible:outline-2 focus-visible:outline-teal-700 ${filter === value ? 'bg-white text-teal-800 shadow-sm' : 'text-slate-500'}`}>{value}</button>)}</div></div>
      {!filtered.length ? <div className="care-card px-5 py-16 text-center"><span className="mx-auto mb-4 flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-50 text-teal-700"><Users size={25} aria-hidden="true" /></span><h2 className="text-base font-semibold text-slate-800">{dataLoading ? 'Loading your patients' : patientDirectory.length ? 'No matching patients' : 'Your patient directory is ready'}</h2><p className="mx-auto mt-2 max-w-md text-sm leading-relaxed text-slate-500">{patientDirectory.length ? 'Try a different search or filter.' : 'Patients assigned to you or booked for a consultation with you will appear here.'}</p></div> : <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((patient) => {
        const appointment = videoAppointment(patient.id);
        return <article key={patient.id} className="care-card flex flex-col p-5"><div className="flex items-start justify-between gap-2"><button type="button" onClick={() => setSelectedId(patient.id)} className="flex min-w-0 items-center gap-3 rounded-lg text-left focus-visible:outline-2 focus-visible:outline-offset-4 focus-visible:outline-teal-700"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-full bg-teal-50 text-sm font-semibold text-teal-800">{patient.name.split(' ').filter(Boolean).slice(0, 2).map((name) => name[0]).join('')}</span><span className="min-w-0"><span className="block truncate text-sm font-semibold text-slate-900">{patient.name}</span><span className="mt-1 block text-xs text-slate-400">{patient.age > 0 ? patient.age + ' years' : 'Age not provided'}</span></span></button><span className={`rounded-full px-2 py-1 text-[9px] font-medium ${hasReadings(patient) && patient.status === 'Critical' ? 'bg-rose-50 text-rose-700' : 'bg-slate-50 text-slate-500'}`}>{hasReadings(patient) ? patient.status : 'No readings'}</span></div><p className="mt-4 text-xs leading-relaxed text-slate-500">{patient.condition || 'Condition not provided'}</p><dl className="mt-4 grid grid-cols-3 gap-2 rounded-xl bg-slate-50 p-3">{[['Heart rate', patient.currentVitals.heartRate > 0 ? patient.currentVitals.heartRate + ' bpm' : '—'], ['SpO₂', patient.currentVitals.spo2 > 0 ? patient.currentVitals.spo2 + '%' : '—'], ['Temperature', patient.lastSyncedTemperature || patient.currentVitals.temperature ? (patient.lastSyncedTemperature || patient.currentVitals.temperature).toFixed(1) + ' °C' : '—']].map(([label, value]) => <div key={label}><dt className="text-[9px] text-slate-400">{label}</dt><dd className="mt-1 text-xs font-semibold text-slate-700">{value}</dd></div>)}</dl><div className="mt-auto flex flex-wrap items-center gap-2 border-t border-slate-100 pt-4 mt-5"><button type="button" onClick={() => setSelectedId(patient.id)} className="mr-auto min-h-10 rounded-lg text-xs font-semibold text-teal-800 focus-visible:outline-2 focus-visible:outline-teal-700">View history</button><button type="button" onClick={() => prescribe(patient)} aria-label={'Prescribe for ' + patient.name} className="flex h-10 w-10 items-center justify-center rounded-xl border border-slate-200 text-slate-500 hover:bg-slate-50 focus-visible:outline-2 focus-visible:outline-teal-700"><FileText size={17} aria-hidden="true" /></button>{appointment && onStartVideoCall && <button type="button" onClick={() => onStartVideoCall(appointment)} aria-label={'Join booked video visit with ' + patient.name} className="flex h-10 w-10 items-center justify-center rounded-xl bg-teal-700 text-white focus-visible:outline-2 focus-visible:outline-teal-700"><Video size={17} aria-hidden="true" /></button>}</div></article>;
      })}</div>}
      {selected && <WorkspaceDialog title={selected.name} onClose={() => setSelectedId('')}><div className="space-y-6"><div className="flex flex-wrap gap-3 text-xs text-slate-500">{selected.email && <span className="flex items-center gap-1.5"><Mail size={14} aria-hidden="true" />{selected.email}</span>}{(selected.phoneNumber || selected.phone) && <span className="flex items-center gap-1.5"><Phone size={14} aria-hidden="true" />{selected.phoneNumber || selected.phone}</span>}</div><PatientHistory patient={selected} /><section><h3 className="mb-3 text-sm font-semibold text-slate-900">Shared medical records</h3>{selectedRecords.length ? <ul className="space-y-3">{selectedRecords.map((record) => <li key={record.id} className="rounded-xl border border-slate-200 p-4"><p className="text-sm font-semibold text-slate-800">{record.title}</p><p className="mt-1 text-xs text-slate-400">{record.type} · {record.date}</p>{record.notes && <p className="my-3 whitespace-pre-wrap text-xs leading-relaxed text-slate-500">{record.notes}</p>}<div className="mt-3"><RecordAttachment record={record} /></div></li>)}</ul> : <p className="rounded-xl bg-slate-50 p-4 text-xs text-slate-400">No shared records are available for this patient.</p>}</section><div className="flex flex-wrap items-center justify-end gap-2 border-t border-slate-100 pt-5"><button type="button" onClick={() => { setNotePatient({ id: selected.id, name: selected.name }); setSelectedId(''); }} className="flex min-h-11 items-center gap-2 rounded-xl border border-slate-200 px-4 text-xs font-semibold text-slate-600"><Plus size={15} aria-hidden="true" />Add a note</button><button type="button" onClick={() => { prescribe(selected); setSelectedId(''); }} className="care-button text-xs"><FileText size={16} aria-hidden="true" />Write prescription</button></div></div></WorkspaceDialog>}
      {notePatient && <ClinicalNoteDialog key={notePatient.id} patient={notePatient} onClose={() => setNotePatient(null)} />}
    </div>
  );
}
